/*
 * @Author: Satya
 * @Date: 2020-06-01 13:54:11
 * @Last Modified by: Satya
 * @Last Modified time: 2020-09-22 19:10:21
 * doc: 该文件似乎非自动生成
 *  追加了[音乐、绘画分类明文]
 */

// This file was automatically generated.  Do not modify.

"use strict";

goog.provide("Blockly.ScratchMsgs.allLocales");

goog.require("Blockly.ScratchMsgs");

Blockly.ScratchMsgs.locales["en"] = {
  /** 控制分类 */
  CONTROL_FOREVER: "%1", // 无线循环
  CONTROL_REPEAT: "%1 %2", // 指定次数循环
  CONTROL_WAIT: "%1 %2", // 延时

  CONTROL_IF: "if %1 then",
  CONTROL_ELSE: "else",
  CONTROL_STOP: "stop",
  CONTROL_STOP_ALL: "all",
  CONTROL_STOP_THIS: "this script",
  CONTROL_STOP_OTHER: "other scripts in sprite",
  CONTROL_WAITUNTIL: "wait until %1",
  CONTROL_REPEATUNTIL: "repeat until %1",
  CONTROL_WHILE: "while %1",
  CONTROL_FOREACH: "for each %1 in %2",
  CONTROL_STARTASCLONE: "when I start as a clone",
  CONTROL_CREATECLONEOF: "create clone of %1",
  CONTROL_CREATECLONEOF_MYSELF: "myself",
  CONTROL_DELETETHISCLONE: "delete this clone",
  CONTROL_COUNTER: "counter",
  CONTROL_INCRCOUNTER: "increment counter",
  CONTROL_CLEARCOUNTER: "clear counter",
  CONTROL_ALLATONCE: "all at once",

  DATA_SETVARIABLETO: "set %1 to %2",
  DATA_CHANGEVARIABLEBY: "change %1 by %2",
  DATA_SHOWVARIABLE: "show variable %1",
  DATA_HIDEVARIABLE: "hide variable %1",
  DATA_ADDTOLIST: "add %1 to %2",
  DATA_DELETEOFLIST: "delete %1 of %2",
  DATA_DELETEALLOFLIST: "delete all of %1",
  DATA_INSERTATLIST: "insert %1 at %2 of %3",
  DATA_REPLACEITEMOFLIST: "replace item %1 of %2 with %3",
  DATA_ITEMOFLIST: "item %1 of %2",
  DATA_ITEMNUMOFLIST: "item # of %1 in %2",
  DATA_LENGTHOFLIST: "length of %1",
  DATA_LISTCONTAINSITEM: "%1 contains %2?",
  DATA_SHOWLIST: "show list %1",
  DATA_HIDELIST: "hide list %1",
  DATA_INDEX_ALL: "all",
  DATA_INDEX_LAST: "last",
  DATA_INDEX_RANDOM: "random",

  /** 事件分类  */
  EVENT_WHENFLAGCLICKED: "%1",
  EVENT_WHENTHISSPRITECLICKED: "%1",
  EVENT_WHENSTAGECLICKED: "when stage clicked",
  EVENT_WHENTOUCHINGOBJECT: "when this sprite touches %1",
  EVENT_WHENBROADCASTRECEIVED: "%1 %2",
  EVENT_WHENBACKDROPSWITCHESTO: "when backdrop switches to %1",
  EVENT_WHENGREATERTHAN: "when %1 > %2",
  EVENT_WHENGREATERTHAN_TIMER: "timer",
  EVENT_WHENGREATERTHAN_LOUDNESS: "loudness",
  EVENT_BROADCAST: "%1 %2",
  EVENT_BROADCASTANDWAIT: "broadcast %1 and wait",
  EVENT_WHENKEYPRESSED: "when %1 key pressed",
  EVENT_WHENKEYPRESSED_SPACE: "space",
  EVENT_WHENKEYPRESSED_LEFT: "left arrow",
  EVENT_WHENKEYPRESSED_RIGHT: "right arrow",
  EVENT_WHENKEYPRESSED_DOWN: "down arrow",
  EVENT_WHENKEYPRESSED_UP: "up arrow",
  EVENT_WHENKEYPRESSED_ANY: "any",

  /** 外观分类  */
  LOOKS_SHOW: "%1", // 显示角色
  LOOKS_HIDE: "%1", // 隐藏角色
  LOOKS_ZOOMIN: "%1", // 缩小角色
  LOOKS_ZOOMOUT: "%1", // 放大角色
  LOOKS_ZOOMRESET: "%1", // 缩放重置
  LOOKS_SWITCHBACKDROPTO: "%1%2", // 背景切换

  /** 运动分类 */
  MOTION_MOVELEFT: "%1 %2 %3", // 左移
  MOTION_MOVERIGHT: "%1 %2 %3", // 右移
  MOTION_MOVEUP: "%1 %2 %3", // 上移
  MOTION_MOVEDOWN: "%1 %2 %3", // 下移
  MOTION_TURNLEFT: "%1 %2", // 左转
  MOTION_TURNRIGHT: "%1 %2", // 右转
  MOTION_JUMP: "%1 %2 %3", // 跳跃
  MOTION_MOVERESET: "%1", // 重置到起始位置
  MOTION_STAGE_SELECTED: "Stage selected: no motion blocks",

  OPERATORS_ADD: "%1 + %2",
  OPERATORS_SUBTRACT: "%1 - %2",
  OPERATORS_MULTIPLY: "%1 * %2",
  OPERATORS_DIVIDE: "%1 / %2",
  OPERATORS_RANDOM: "pick random %1 to %2",
  OPERATORS_GT: "%1 > %2",
  OPERATORS_LT: "%1 < %2",
  OPERATORS_EQUALS: "%1 = %2",
  OPERATORS_AND: "%1 and %2",
  OPERATORS_OR: "%1 or %2",
  OPERATORS_NOT: "not %1",
  OPERATORS_JOIN: "join %1 %2",
  OPERATORS_JOIN_APPLE: "apple",
  OPERATORS_JOIN_BANANA: "banana",
  OPERATORS_LETTEROF: "letter %1 of %2",
  OPERATORS_LETTEROF_APPLE: "a",
  OPERATORS_LENGTH: "length of %1",
  OPERATORS_CONTAINS: "%1 contains %2?",
  OPERATORS_MOD: "%1 mod %2",
  OPERATORS_ROUND: "round %1",
  OPERATORS_MATHOP: "%1 of %2",
  OPERATORS_MATHOP_ABS: "abs",
  OPERATORS_MATHOP_FLOOR: "floor",
  OPERATORS_MATHOP_CEILING: "ceiling",
  OPERATORS_MATHOP_SQRT: "sqrt",
  OPERATORS_MATHOP_SIN: "sin",
  OPERATORS_MATHOP_COS: "cos",
  OPERATORS_MATHOP_TAN: "tan",
  OPERATORS_MATHOP_ASIN: "asin",
  OPERATORS_MATHOP_ACOS: "acos",
  OPERATORS_MATHOP_ATAN: "atan",
  OPERATORS_MATHOP_LN: "ln",
  OPERATORS_MATHOP_LOG: "log",
  OPERATORS_MATHOP_EEXP: "e ^",
  OPERATORS_MATHOP_10EXP: "10 ^",
  PROCEDURES_DEFINITION: "define %1",
  SENSING_TOUCHINGOBJECT: "touching %1?",
  SENSING_TOUCHINGOBJECT_POINTER: "mouse-pointer",
  SENSING_TOUCHINGOBJECT_EDGE: "edge",
  SENSING_TOUCHINGCOLOR: "touching color %1?",
  SENSING_COLORISTOUCHINGCOLOR: "color %1 is touching %2?",
  SENSING_DISTANCETO: "distance to %1",
  SENSING_DISTANCETO_POINTER: "mouse-pointer",
  SENSING_ASKANDWAIT: "ask %1 and wait",
  SENSING_ASK_TEXT: "What's your name?",
  SENSING_ANSWER: "answer",
  SENSING_KEYPRESSED: "key %1 pressed?",
  SENSING_MOUSEDOWN: "mouse down?",
  SENSING_MOUSEX: "mouse x",
  SENSING_MOUSEY: "mouse y",
  SENSING_SETDRAGMODE: "set drag mode %1",
  SENSING_SETDRAGMODE_DRAGGABLE: "draggable",
  SENSING_SETDRAGMODE_NOTDRAGGABLE: "not draggable",
  SENSING_LOUDNESS: "loudness",
  SENSING_LOUD: "loud?",
  SENSING_TIMER: "timer",
  SENSING_RESETTIMER: "reset timer",
  SENSING_OF: "%1 of %2",
  SENSING_OF_XPOSITION: "x position",
  SENSING_OF_YPOSITION: "y position",
  SENSING_OF_DIRECTION: "direction",
  SENSING_OF_COSTUMENUMBER: "costume #",
  SENSING_OF_COSTUMENAME: "costume name",
  SENSING_OF_SIZE: "size",
  SENSING_OF_VOLUME: "volume",
  SENSING_OF_BACKDROPNUMBER: "backdrop #",
  SENSING_OF_BACKDROPNAME: "backdrop name",
  SENSING_OF_STAGE: "Stage",
  SENSING_CURRENT: "current %1",
  SENSING_CURRENT_YEAR: "year",
  SENSING_CURRENT_MONTH: "month",
  SENSING_CURRENT_DATE: "date",
  SENSING_CURRENT_DAYOFWEEK: "day of week",
  SENSING_CURRENT_HOUR: "hour",
  SENSING_CURRENT_MINUTE: "minute",
  SENSING_CURRENT_SECOND: "second",
  SENSING_DAYSSINCE2000: "days since 2000",
  SENSING_USERNAME: "username",
  SENSING_USERID: "user id",
  SOUND_PLAY: "start sound %1",
  SOUND_PLAYUNTILDONE: "play sound %1 until done",
  SOUND_STOPALLSOUNDS: "stop all sounds",
  SOUND_SETEFFECTO: "set %1 effect to %2",
  SOUND_CHANGEEFFECTBY: "change %1 effect by %2",
  SOUND_CLEAREFFECTS: "clear sound effects",
  SOUND_EFFECTS_PITCH: "pitch",
  SOUND_EFFECTS_PAN: "pan left/right",
  SOUND_CHANGEVOLUMEBY: "change volume by %1",
  SOUND_SETVOLUMETO: "set volume to %1%",
  SOUND_VOLUME: "volume",
  SOUND_RECORD: "record...",
  // 追加绘画分类 积木块明文
  PEN_CLEAR: "%1 erase all",
  PEN_DOWN: "%1 pen down",
  PEN_UP: "%1 pen up",
  PEN_SETCOLORTO: "%1 %2",
  // 追加音乐分类 积木块明文
  MUSIC_PLAYDRUMFORBEATS: "%1",

  // 分类的明文
  CATEGORY_MOTION: "Motion",
  CATEGORY_LOOKS: "Looks",
  CATEGORY_SOUND: "Sound",
  CATEGORY_EVENTS: "Events",
  CATEGORY_CONTROL: "Control",
  CATEGORY_SENSING: "Sensing",
  CATEGORY_OPERATORS: "Operators",
  CATEGORY_VARIABLES: "Variables",
  CATEGORY_MYBLOCKS: "My Blocks",
  // 追加两个分裂
  CATEGORY_MUSIC: "Music",
  CATEGORY_PEN: "Pen",
  DUPLICATE: "Duplicate",
  DELETE: "Delete",
  ADD_COMMENT: "Add Comment",
  REMOVE_COMMENT: "Remove Comment",
  DELETE_BLOCK: "Delete Block",
  DELETE_X_BLOCKS: "Delete %1 Blocks",
  DELETE_ALL_BLOCKS: "Delete all %1 blocks?",
  CLEAN_UP: "Clean up Blocks",
  HELP: "Help",
  UNDO: "Undo",
  REDO: "Redo",
  EDIT_PROCEDURE: "Edit",
  SHOW_PROCEDURE_DEFINITION: "Go to definition",
  WORKSPACE_COMMENT_DEFAULT_TEXT: "Say something...",
  COLOUR_HUE_LABEL: "Color",
  COLOUR_SATURATION_LABEL: "Saturation",
  COLOUR_BRIGHTNESS_LABEL: "Brightness",
  CHANGE_VALUE_TITLE: "Change value:",
  RENAME_VARIABLE: "Rename variable",
  RENAME_VARIABLE_TITLE: 'Rename all "%1" variables to:',
  RENAME_VARIABLE_MODAL_TITLE: "Rename Variable",
  NEW_VARIABLE: "Make a Variable",
  NEW_VARIABLE_TITLE: "New variable name:",
  VARIABLE_MODAL_TITLE: "New Variable",
  VARIABLE_ALREADY_EXISTS: 'A variable named "%1" already exists.',
  VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE:
    'A variable named "%1" already exists for another variable of type "%2".',
  DELETE_VARIABLE_CONFIRMATION: 'Delete %1 uses of the "%2" variable?',
  CANNOT_DELETE_VARIABLE_PROCEDURE:
    'Can\'t delete the variable "%1" because it\'s part of the definition of the function "%2"',
  DELETE_VARIABLE: 'Delete the "%1" variable',
  NEW_PROCEDURE: "Make a Block",
  PROCEDURE_ALREADY_EXISTS: 'A procedure named "%1" already exists.',
  PROCEDURE_DEFAULT_NAME: "block name",
  NEW_LIST: "Make a List",
  NEW_LIST_TITLE: "New list name:",
  LIST_MODAL_TITLE: "New List",
  LIST_ALREADY_EXISTS: 'A list named "%1" already exists.',
  RENAME_LIST_TITLE: 'Rename all "%1" lists to:',
  RENAME_LIST_MODAL_TITLE: "Rename List",
  DEFAULT_LIST_ITEM: "thing",
  DELETE_LIST: 'Delete the "%1" list',
  RENAME_LIST: "Rename list",
  NEW_BROADCAST_MESSAGE: "New message",
  NEW_BROADCAST_MESSAGE_TITLE: "New message name:",
  BROADCAST_MODAL_TITLE: "New Message",
  DEFAULT_BROADCAST_MESSAGE_NAME: "message1",
};

Blockly.ScratchMsgs.locales["zh-cn"] = {
  /** 控制分类 */
  CONTROL_FOREVER: "%1", // 无线循环
  CONTROL_REPEAT: "%1 %2", // 指定次数循环
  CONTROL_WAIT: "%1 %2", // 延时

  CONTROL_IF: "如果 %1 那么",
  CONTROL_ELSE: "否则",
  CONTROL_STOP: "停止",
  CONTROL_STOP_ALL: "全部脚本",
  CONTROL_STOP_THIS: "这个脚本",
  CONTROL_STOP_OTHER: "该角色的其他脚本",
  CONTROL_WAITUNTIL: "等待 %1",
  CONTROL_REPEATUNTIL: "重复执行直到 %1",
  CONTROL_WHILE: "当 %1 重复执行",
  CONTROL_FOREACH: "对于 %2 中的每个 %1",
  CONTROL_STARTASCLONE: "当作为克隆体启动时",
  CONTROL_CREATECLONEOF: "克隆 %1",
  CONTROL_CREATECLONEOF_MYSELF: "自己",
  CONTROL_DELETETHISCLONE: "删除此克隆体",
  CONTROL_COUNTER: "计数器",
  CONTROL_INCRCOUNTER: "计数器加一",
  CONTROL_CLEARCOUNTER: "计数器归零",
  CONTROL_ALLATONCE: "所有脚本",

  DATA_SETVARIABLETO: "将 %1 设为 %2",
  DATA_CHANGEVARIABLEBY: "将 %1 增加 %2",
  DATA_SHOWVARIABLE: "显示变量 %1",
  DATA_HIDEVARIABLE: "隐藏变量 %1",
  DATA_ADDTOLIST: "将 %1 加入 %2",
  DATA_DELETEOFLIST: "删除 %2 的第 %1 项",
  DATA_DELETEALLOFLIST: "删除 %1 的全部项目",
  DATA_INSERTATLIST: "在 %3 的第 %2 项前插入 %1",
  DATA_REPLACEITEMOFLIST: "将 %2 的第 %1 项替换为 %3",
  DATA_ITEMOFLIST: "%2 的第 %1 项",
  DATA_ITEMNUMOFLIST: "%2 中第一个 %1 的编号",
  DATA_LENGTHOFLIST: "%1 的项目数",
  DATA_LISTCONTAINSITEM: "%1 包含 %2 ?",
  DATA_SHOWLIST: "显示列表 %1",
  DATA_HIDELIST: "隐藏列表 %1",
  DATA_INDEX_ALL: "全部",
  DATA_INDEX_LAST: "末尾",
  DATA_INDEX_RANDOM: "随机",

  /** 事件分类  */
  EVENT_WHENFLAGCLICKED: " %1",
  EVENT_WHENTHISSPRITECLICKED: "%1",
  EVENT_WHENSTAGECLICKED: "当舞台被点击",
  EVENT_WHENTOUCHINGOBJECT: "当该角色碰到 %1",
  EVENT_WHENBROADCASTRECEIVED: "%1 %2",
  EVENT_WHENBACKDROPSWITCHESTO: "当背景换成 %1",
  EVENT_WHENGREATERTHAN: "当 %1 > %2",
  EVENT_WHENGREATERTHAN_TIMER: "计时器",
  EVENT_WHENGREATERTHAN_LOUDNESS: "响度",
  EVENT_BROADCAST: "%1 %2",
  EVENT_BROADCASTANDWAIT: "广播 %1 并等待",
  EVENT_WHENKEYPRESSED: "当按下 %1 键",
  EVENT_WHENKEYPRESSED_SPACE: "空格",
  EVENT_WHENKEYPRESSED_LEFT: "←",
  EVENT_WHENKEYPRESSED_RIGHT: "→",
  EVENT_WHENKEYPRESSED_DOWN: "↓",
  EVENT_WHENKEYPRESSED_UP: "↑",
  EVENT_WHENKEYPRESSED_ANY: "任意",

  /** 外观分类  */
  LOOKS_SHOW: "%1", // 显示角色
  LOOKS_HIDE: "%1", // 隐藏角色
  LOOKS_ZOOMIN: "%1", // 缩小角色
  LOOKS_ZOOMOUT: "%1", // 放大角色
  LOOKS_ZOOMRESET: "%1", // 缩放重置
  LOOKS_SWITCHBACKDROPTO: "%1%2", // 背景切换

  /** 运动分类 */
  MOTION_MOVELEFT: "%1 %2 %3", // 左移
  MOTION_MOVERIGHT: "%1 %2 %3", // 右移
  MOTION_MOVEUP: "%1 %2 %3", // 上移
  MOTION_MOVEDOWN: "%1 %2 %3", // 下移
  MOTION_TURNLEFT: "%1 %2", // 左转
  MOTION_TURNRIGHT: "%1 %2", // 右转
  MOTION_JUMP: "%1 %2 %3", // 跳跃
  MOTION_MOVERESET: "%1", // 重置到起始位置
  MOTION_STAGE_SELECTED: "选中了舞台：不可使用运动类积木",

  OPERATORS_ADD: "%1 + %2",
  OPERATORS_SUBTRACT: "%1 - %2",
  OPERATORS_MULTIPLY: "%1 * %2",
  OPERATORS_DIVIDE: "%1 / %2",
  OPERATORS_RANDOM: "在 %1 和 %2 之间取随机数",
  OPERATORS_GT: "%1 > %2",
  OPERATORS_LT: "%1 < %2",
  OPERATORS_EQUALS: "%1 = %2",
  OPERATORS_AND: "%1 与 %2",
  OPERATORS_OR: "%1 或 %2",
  OPERATORS_NOT: "%1 不成立",
  OPERATORS_JOIN: "连接 %1 和 %2",
  OPERATORS_JOIN_APPLE: "苹果",
  OPERATORS_JOIN_BANANA: "香蕉",
  OPERATORS_LETTEROF: "%2 的第 %1 个字符",
  OPERATORS_LETTEROF_APPLE: "果",
  OPERATORS_LENGTH: "%1 的字符数",
  OPERATORS_CONTAINS: "%1 包含 %2 ?",
  OPERATORS_MOD: "%1 除以 %2 的余数",
  OPERATORS_ROUND: "四舍五入 %1",
  OPERATORS_MATHOP: "%1 %2",
  OPERATORS_MATHOP_ABS: "绝对值",
  OPERATORS_MATHOP_FLOOR: "向下取整",
  OPERATORS_MATHOP_CEILING: "向上取整",
  OPERATORS_MATHOP_SQRT: "平方根",
  OPERATORS_MATHOP_SIN: "sin",
  OPERATORS_MATHOP_COS: "cos",
  OPERATORS_MATHOP_TAN: "tan",
  OPERATORS_MATHOP_ASIN: "asin",
  OPERATORS_MATHOP_ACOS: "acos",
  OPERATORS_MATHOP_ATAN: "atan",
  OPERATORS_MATHOP_LN: "ln",
  OPERATORS_MATHOP_LOG: "log",
  OPERATORS_MATHOP_EEXP: "e ^",
  OPERATORS_MATHOP_10EXP: "10 ^",
  PROCEDURES_DEFINITION: "定义 %1",
  SENSING_TOUCHINGOBJECT: "碰到 %1 ?",
  SENSING_TOUCHINGOBJECT_POINTER: "鼠标指针",
  SENSING_TOUCHINGOBJECT_EDGE: "舞台边缘",
  SENSING_TOUCHINGCOLOR: "碰到颜色 %1 ?",
  SENSING_COLORISTOUCHINGCOLOR: "颜色 %1 碰到 %2 ?",
  SENSING_DISTANCETO: "到 %1 的距离",
  SENSING_DISTANCETO_POINTER: "鼠标指针",
  SENSING_ASKANDWAIT: "询问 %1 并等待",
  SENSING_ASK_TEXT: "你叫什么名字？",
  SENSING_ANSWER: "回答",
  SENSING_KEYPRESSED: "按下 %1 键?",
  SENSING_MOUSEDOWN: "按下鼠标?",
  SENSING_MOUSEX: "鼠标的x坐标",
  SENSING_MOUSEY: "鼠标的y坐标",
  SENSING_SETDRAGMODE: "将拖动模式设为 %1",
  SENSING_SETDRAGMODE_DRAGGABLE: "可拖动",
  SENSING_SETDRAGMODE_NOTDRAGGABLE: "不可拖动",
  SENSING_LOUDNESS: "响度",
  SENSING_LOUD: "响声？",
  SENSING_TIMER: "计时器",
  SENSING_RESETTIMER: "计时器归零",
  SENSING_OF: "%2 的 %1",
  SENSING_OF_XPOSITION: "x 坐标",
  SENSING_OF_YPOSITION: "y 坐标",
  SENSING_OF_DIRECTION: "方向",
  SENSING_OF_COSTUMENUMBER: "造型编号",
  SENSING_OF_COSTUMENAME: "造型名称",
  SENSING_OF_SIZE: "大小",
  SENSING_OF_VOLUME: "音量",
  SENSING_OF_BACKDROPNUMBER: "背景编号",
  SENSING_OF_BACKDROPNAME: "背景名称",
  SENSING_OF_STAGE: "舞台",
  SENSING_CURRENT: "当前时间的 %1",
  SENSING_CURRENT_YEAR: "年",
  SENSING_CURRENT_MONTH: "月",
  SENSING_CURRENT_DATE: "日",
  SENSING_CURRENT_DAYOFWEEK: "星期",
  SENSING_CURRENT_HOUR: "时",
  SENSING_CURRENT_MINUTE: "分",
  SENSING_CURRENT_SECOND: "秒",
  SENSING_DAYSSINCE2000: "2000年至今的天数",
  SENSING_USERNAME: "用户名",
  SENSING_USERID: "用户id",
  SOUND_PLAY: "播放声音 %1",
  SOUND_PLAYUNTILDONE: "播放声音 %1 等待播完",
  SOUND_STOPALLSOUNDS: "停止所有声音",
  SOUND_SETEFFECTO: "将 %1 音效设为 %2",
  SOUND_CHANGEEFFECTBY: "将 %1 音效增加 %2",
  SOUND_CLEAREFFECTS: "清除音效",
  SOUND_EFFECTS_PITCH: "音调",
  SOUND_EFFECTS_PAN: "左右平衡",
  SOUND_CHANGEVOLUMEBY: "将音量增加 %1",
  SOUND_SETVOLUMETO: "将音量设为 %1%",
  SOUND_VOLUME: "音量",
  SOUND_RECORD: "录制…",
  // 追加绘画分类 积木块明文
  PEN_CLEAR: "%1 全部擦除",
  PEN_DOWN: "%1 落笔",
  PEN_UP: "%1 抬笔",
  PEN_SETCOLORTO: "%1 %2",
  // 追加音乐分类 积木块明文
  MUSIC_PLAYDRUMFORBEATS: "%1",
  // 分类的明文
  CATEGORY_MOTION: "运动",
  CATEGORY_LOOKS: "外观",
  CATEGORY_SOUND: "声音",
  CATEGORY_EVENTS: "事件",
  CATEGORY_CONTROL: "控制",
  CATEGORY_SENSING: "侦测",
  CATEGORY_OPERATORS: "运算",
  CATEGORY_VARIABLES: "变量",
  CATEGORY_MYBLOCKS: "自制积木",
  // 追加两个分裂
  CATEGORY_MUSIC: "音乐",
  CATEGORY_PEN: "绘画",
  DUPLICATE: "复制",
  DELETE: "删除",
  ADD_COMMENT: "添加注释",
  REMOVE_COMMENT: "删除注释",
  DELETE_BLOCK: "删除",
  DELETE_X_BLOCKS: "删除 %1 积木",
  DELETE_ALL_BLOCKS: "删除全部 %1 积木？",
  CLEAN_UP: "整理积木",
  HELP: "帮助",
  UNDO: "撤销",
  REDO: "重做",
  EDIT_PROCEDURE: "编辑",
  SHOW_PROCEDURE_DEFINITION: "查看定义",
  WORKSPACE_COMMENT_DEFAULT_TEXT: "说些什么……",
  COLOUR_HUE_LABEL: "颜色",
  COLOUR_SATURATION_LABEL: "饱和度",
  COLOUR_BRIGHTNESS_LABEL: "亮度",
  CHANGE_VALUE_TITLE: "更改变量：",
  RENAME_VARIABLE: "修改变量名",
  RENAME_VARIABLE_TITLE: "将所有的「%1」变量名改为：",
  RENAME_VARIABLE_MODAL_TITLE: "修改变量名",
  NEW_VARIABLE: "建立一个变量",
  NEW_VARIABLE_TITLE: "新变量名：",
  VARIABLE_MODAL_TITLE: "新建变量",
  VARIABLE_ALREADY_EXISTS: "已经存在名为「%1」的变量。",
  VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE:
    "已经存在一个名为「%1」的变量，其类型为「%2」。",
  DELETE_VARIABLE_CONFIRMATION: "删除%1处「%2」变量吗？",
  CANNOT_DELETE_VARIABLE_PROCEDURE:
    "无法删除变量「%1」，因为函数「%2」的定义中用到了它",
  DELETE_VARIABLE: "删除变量「%1」",
  NEW_PROCEDURE: "制作新的积木",
  PROCEDURE_ALREADY_EXISTS: "已经存在名为「%1」的程序。",
  PROCEDURE_DEFAULT_NAME: "积木名称",
  NEW_LIST: "建立一个列表",
  NEW_LIST_TITLE: "新的列表名：",
  LIST_MODAL_TITLE: "新建列表",
  LIST_ALREADY_EXISTS: "名为 「%1」 的列表已存在。",
  RENAME_LIST_TITLE: "将所有的「%1」列表改名为：",
  RENAME_LIST_MODAL_TITLE: "修改列表名",
  DEFAULT_LIST_ITEM: "东西",
  DELETE_LIST: "删除「%1」列表",
  RENAME_LIST: "修改列表名",
  NEW_BROADCAST_MESSAGE: "新消息",
  NEW_BROADCAST_MESSAGE_TITLE: "新消息的名称：",
  BROADCAST_MODAL_TITLE: "新消息",
  DEFAULT_BROADCAST_MESSAGE_NAME: "消息1",
};

Blockly.ScratchMsgs.locales["zh-tw"] = {
  /** 控制分类 */
  CONTROL_FOREVER: "%1", // 无线循环
  CONTROL_REPEAT: "%1 %2", // 指定次数循环
  CONTROL_WAIT: "%1 %2", // 延时
  CONTROL_IF: "如果 %1 那麼",
  CONTROL_ELSE: "否則",
  CONTROL_STOP: "停止",
  CONTROL_STOP_ALL: "全部",
  CONTROL_STOP_THIS: "這個程式",
  CONTROL_STOP_OTHER: "這個物件的其它程式",
  CONTROL_WAITUNTIL: "等待直到 %1",
  CONTROL_REPEATUNTIL: "重複直到 %1",
  CONTROL_WHILE: "當 %1",
  CONTROL_FOREACH: "計數 %1 於 %2",
  CONTROL_STARTASCLONE: "當分身產生",
  CONTROL_CREATECLONEOF: "建立 %1 的分身",
  CONTROL_CREATECLONEOF_MYSELF: "自己",
  CONTROL_DELETETHISCLONE: "分身刪除",
  CONTROL_COUNTER: "計數器",
  CONTROL_INCRCOUNTER: "計數器累計",
  CONTROL_CLEARCOUNTER: "計數器重置",
  CONTROL_ALLATONCE: "全部一起",

  DATA_SETVARIABLETO: "變數 %1 設為 %2",
  DATA_CHANGEVARIABLEBY: "變數 %1 改變 %2",
  DATA_SHOWVARIABLE: "變數 %1 顯示",
  DATA_HIDEVARIABLE: "變數 %1 隱藏",
  DATA_ADDTOLIST: "添加 %1 到 %2",
  DATA_DELETEOFLIST: "刪除 %2 的第 %1 項",
  DATA_DELETEALLOFLIST: "刪除 %1 的所有項目",
  DATA_INSERTATLIST: "插入 %1 到 %3 的第 %2 項",
  DATA_REPLACEITEMOFLIST: "替換 %2 的第 %1 項為 %3",
  DATA_ITEMOFLIST: "%2 的第 %1 項",
  DATA_ITEMNUMOFLIST: "%1 在 %2 裡的項目編號",
  DATA_LENGTHOFLIST: "清單 %1 的長度",
  DATA_LISTCONTAINSITEM: "清單 %1 包含 %2？",
  DATA_SHOWLIST: "清單 %1 顯示",
  DATA_HIDELIST: "清單 %1 隱藏",
  DATA_INDEX_ALL: "全部",
  DATA_INDEX_LAST: "末",
  DATA_INDEX_RANDOM: "隨機",

  /** 事件分类  */
  EVENT_WHENFLAGCLICKED: "當 %1 被點擊",
  EVENT_WHENTHISSPRITECLICKED: "%1",
  EVENT_WHENSTAGECLICKED: "當舞台被點擊",
  EVENT_WHENTOUCHINGOBJECT: "當角色碰到 %1",
  EVENT_WHENBROADCASTRECEIVED: "%1 %2",
  EVENT_WHENBACKDROPSWITCHESTO: "當背景換成 %1",
  EVENT_WHENGREATERTHAN: "當 %1 > %2",
  EVENT_WHENGREATERTHAN_TIMER: "計時器",
  EVENT_WHENGREATERTHAN_LOUDNESS: "聲音響度",
  EVENT_BROADCAST: "%1 %2",
  EVENT_BROADCASTANDWAIT: "廣播訊息 %1 並等待",
  EVENT_WHENKEYPRESSED: "當 %1 鍵被按下",
  EVENT_WHENKEYPRESSED_SPACE: "空白",
  EVENT_WHENKEYPRESSED_LEFT: "向左",
  EVENT_WHENKEYPRESSED_RIGHT: "向右",
  EVENT_WHENKEYPRESSED_DOWN: "向下",
  EVENT_WHENKEYPRESSED_UP: "向上",
  EVENT_WHENKEYPRESSED_ANY: "任何",

  /** 外观分类  */
  LOOKS_SHOW: "%1", // 显示角色
  LOOKS_HIDE: "%1", // 隐藏角色
  LOOKS_ZOOMIN: "%1", // 缩小角色
  LOOKS_ZOOMOUT: "%1", // 放大角色
  LOOKS_ZOOMRESET: "%1", // 缩放重置
  LOOKS_SWITCHBACKDROPTO: "%1%2", // 背景切换

  /** 运动分类 */
  MOTION_MOVELEFT: "%1 %2 %3", // 左移
  MOTION_MOVERIGHT: "%1 %2 %3", // 右移
  MOTION_MOVEUP: "%1 %2 %3", // 上移
  MOTION_MOVEDOWN: "%1 %2 %3", // 下移
  MOTION_TURNLEFT: "%1 %2", // 左转
  MOTION_TURNRIGHT: "%1 %2", // 右转
  MOTION_JUMP: "%1 %2 %3", // 跳跃
  MOTION_MOVERESET: "%1", // 重置到起始位置
  MOTION_STAGE_SELECTED: "目前選擇的物件是「舞台」：無可用的動作積木",

  OPERATORS_ADD: "%1 + %2",
  OPERATORS_SUBTRACT: "%1 - %2",
  OPERATORS_MULTIPLY: "%1 * %2",
  OPERATORS_DIVIDE: "%1 / %2",
  OPERATORS_RANDOM: "隨機取數 %1 到 %2",
  OPERATORS_GT: "%1 > %2",
  OPERATORS_LT: "%1 < %2",
  OPERATORS_EQUALS: "%1 = %2",
  OPERATORS_AND: "%1 且 %2",
  OPERATORS_OR: "%1 或 %2",
  OPERATORS_NOT: "%1 不成立",
  OPERATORS_JOIN: "字串組合 %1 %2",
  OPERATORS_JOIN_APPLE: "apple",
  OPERATORS_JOIN_BANANA: "banana",
  OPERATORS_LETTEROF: "字串 %2 的第 %1 字",
  OPERATORS_LETTEROF_APPLE: "a",
  OPERATORS_LENGTH: "字串 %1 的長度",
  OPERATORS_CONTAINS: "字串 %1 包含 %2？",
  OPERATORS_MOD: "%1 除以 %2 的餘數",
  OPERATORS_ROUND: "四捨五入數值 %1",
  OPERATORS_MATHOP: "%1 數值 %2",
  OPERATORS_MATHOP_ABS: "絕對值",
  OPERATORS_MATHOP_FLOOR: "無條件捨去",
  OPERATORS_MATHOP_CEILING: "無條件進位",
  OPERATORS_MATHOP_SQRT: "平方根",
  OPERATORS_MATHOP_SIN: "sin",
  OPERATORS_MATHOP_COS: "cos",
  OPERATORS_MATHOP_TAN: "tan",
  OPERATORS_MATHOP_ASIN: "asin",
  OPERATORS_MATHOP_ACOS: "acos",
  OPERATORS_MATHOP_ATAN: "atan",
  OPERATORS_MATHOP_LN: "ln",
  OPERATORS_MATHOP_LOG: "log",
  OPERATORS_MATHOP_EEXP: "e ^",
  OPERATORS_MATHOP_10EXP: "10 ^",
  PROCEDURES_DEFINITION: "定義 %1",
  SENSING_TOUCHINGOBJECT: "碰到 %1？",
  SENSING_TOUCHINGOBJECT_POINTER: "鼠標",
  SENSING_TOUCHINGOBJECT_EDGE: "邊緣",
  SENSING_TOUCHINGCOLOR: "碰到顏色 %1？",
  SENSING_COLORISTOUCHINGCOLOR: "顏色 %1 碰到 顏色 %2？",
  SENSING_DISTANCETO: "與 %1 的間距",
  SENSING_DISTANCETO_POINTER: "鼠標",
  SENSING_ASKANDWAIT: "詢問 %1 並等待",
  SENSING_ASK_TEXT: "你的名字是？",
  SENSING_ANSWER: "詢問的答案",
  SENSING_KEYPRESSED: "%1 鍵被按下？",
  SENSING_MOUSEDOWN: "滑鼠鍵被按下？",
  SENSING_MOUSEX: "鼠標的 x",
  SENSING_MOUSEY: "鼠標的 y",
  SENSING_SETDRAGMODE: "拖曳方式設為 %1",
  SENSING_SETDRAGMODE_DRAGGABLE: "可拖曳",
  SENSING_SETDRAGMODE_NOTDRAGGABLE: "不可拖曳",
  SENSING_LOUDNESS: "聲音響度",
  SENSING_LOUD: "大聲？",
  SENSING_TIMER: "計時器",
  SENSING_RESETTIMER: "計時器重置",
  SENSING_OF: "%2 的 %1",
  SENSING_OF_XPOSITION: "x 座標",
  SENSING_OF_YPOSITION: "y 座標",
  SENSING_OF_DIRECTION: "方向",
  SENSING_OF_COSTUMENUMBER: "造型編號",
  SENSING_OF_COSTUMENAME: "造型名稱",
  SENSING_OF_SIZE: "尺寸",
  SENSING_OF_VOLUME: "音量",
  SENSING_OF_BACKDROPNUMBER: "背景編號",
  SENSING_OF_BACKDROPNAME: "背景名稱",
  SENSING_OF_STAGE: "舞台",
  SENSING_CURRENT: "目前時間的 %1",
  SENSING_CURRENT_YEAR: "年",
  SENSING_CURRENT_MONTH: "月",
  SENSING_CURRENT_DATE: "日",
  SENSING_CURRENT_DAYOFWEEK: "週",
  SENSING_CURRENT_HOUR: "時",
  SENSING_CURRENT_MINUTE: "分",
  SENSING_CURRENT_SECOND: "秒",
  SENSING_DAYSSINCE2000: "2000年迄今日數",
  SENSING_USERNAME: "用戶名稱",
  SENSING_USERID: "用戶 ID",
  SOUND_PLAY: "播放音效 %1",
  SOUND_PLAYUNTILDONE: "播放音效 %1 直到結束",
  SOUND_STOPALLSOUNDS: "停播所有音效",
  SOUND_SETEFFECTO: "聲音效果 %1 設為 %2",
  SOUND_CHANGEEFFECTBY: "聲音效果 %1 改變 %2",
  SOUND_CLEAREFFECTS: "聲音效果清除",
  SOUND_EFFECTS_PITCH: "音高",
  SOUND_EFFECTS_PAN: "聲道左/右",
  SOUND_CHANGEVOLUMEBY: "音量改變 %1",
  SOUND_SETVOLUMETO: "音量設為 %1%",
  SOUND_VOLUME: "音量",
  SOUND_RECORD: "錄音…",
  // 追加绘画分类 积木块明文
  PEN_CLEAR: "%1 全部擦除",
  PEN_DOWN: "%1 落笔",
  PEN_UP: "%1 抬笔",
  PEN_SETCOLORTO: "%1 %2",
  // 追加音乐分类 积木块明文
  MUSIC_PLAYDRUMFORBEATS: "%1",
  // 分类的明文
  CATEGORY_MOTION: "動作",
  CATEGORY_LOOKS: "外觀",
  CATEGORY_SOUND: "音效",
  CATEGORY_EVENTS: "事件",
  CATEGORY_CONTROL: "控制",
  CATEGORY_SENSING: "偵測",
  CATEGORY_OPERATORS: "運算",
  CATEGORY_VARIABLES: "變數",
  CATEGORY_MYBLOCKS: "函式積木",
  // 追加两个分裂
  CATEGORY_MUSIC: "音樂",
  CATEGORY_PEN: "繪畫",
  DUPLICATE: "複製",
  DELETE: "刪除",
  ADD_COMMENT: "添加註解",
  REMOVE_COMMENT: "移除註解",
  DELETE_BLOCK: "刪除積木",
  DELETE_X_BLOCKS: "刪除 %1 個積木",
  DELETE_ALL_BLOCKS: "要刪除全部（%1 個）積木？",
  CLEAN_UP: "整理積木",
  HELP: "幫助",
  UNDO: "復原",
  REDO: "重做",
  EDIT_PROCEDURE: "編輯",
  SHOW_PROCEDURE_DEFINITION: "移至定義",
  WORKSPACE_COMMENT_DEFAULT_TEXT: "說些什麼…",
  COLOUR_HUE_LABEL: "顏色",
  COLOUR_SATURATION_LABEL: "彩度",
  COLOUR_BRIGHTNESS_LABEL: "亮度",
  CHANGE_VALUE_TITLE: "改成：",
  RENAME_VARIABLE: "重新命名變數",
  RENAME_VARIABLE_TITLE: "將變數 %1  重新命名為：",
  RENAME_VARIABLE_MODAL_TITLE: "重新命名變數",
  NEW_VARIABLE: "建立一個變數",
  NEW_VARIABLE_TITLE: "新變數的名稱",
  VARIABLE_MODAL_TITLE: "新的變數",
  VARIABLE_ALREADY_EXISTS: "變數名稱「%1」已經被使用。",
  VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE:
    "變數名稱「%1」已經被使用在 %2 型別了。",
  DELETE_VARIABLE_CONFIRMATION: "刪除正在使用的變數 %2 的 %1 個地方？",
  CANNOT_DELETE_VARIABLE_PROCEDURE:
    "無法刪除變數 %1，因為它是函式 %2 定義中的一部分。",
  DELETE_VARIABLE: "刪除變數 %1",
  NEW_PROCEDURE: "建立一個積木",
  PROCEDURE_ALREADY_EXISTS: "程序名稱「%1」已經被使用。",
  PROCEDURE_DEFAULT_NAME: "積木名稱",
  NEW_LIST: "建立一個清單",
  NEW_LIST_TITLE: "新清單的名稱",
  LIST_MODAL_TITLE: "新的清單",
  LIST_ALREADY_EXISTS: "清單名稱「%1」已經被使用。",
  RENAME_LIST_TITLE: "將清單 %1 重新命名為：",
  RENAME_LIST_MODAL_TITLE: "重新命名清單",
  DEFAULT_LIST_ITEM: "thing",
  DELETE_LIST: "刪除清單 %1",
  RENAME_LIST: "重新命名清單",
  NEW_BROADCAST_MESSAGE: "新的訊息",
  NEW_BROADCAST_MESSAGE_TITLE: "新訊息的名稱",
  BROADCAST_MODAL_TITLE: "新的訊息",
  DEFAULT_BROADCAST_MESSAGE_NAME: "message1",
};
// End of combined translations
