export default [{
	"id": 1,
	"name": "散货船",
	"label": "dashboard.main.vesselSet.ship1",
	"url": "bulk-cargo.jpg"
}, {
	"id": 2,
	"name": "集装箱船",
	"label": "dashboard.main.vesselSet.ship5",
	"url": "container-ship.jpg"
}, {
	"id": 3,
	"name": "多用途船",
	"url": "placeholder.png"
}, {
	"id": 4,
	"name": "杂货船",
	"label": "dashboard.main.vesselSet.ship2",
	"url": "general-cargo.jpg"
}, {
	"id": 5,
	"name": "油船",
	"label": "dashboard.main.vesselSet.ship4",
	"url": "tanker.jpg"
}, {
	"id": 6,
	"name": "液化气船",
	"url": "placeholder.png"
}, {
	"id": 7,
	"name": "化学品船",
	"label": "dashboard.main.vesselSet.ship3",
	"url": "chemical-tanker.jpg"
}, {
	"id": 8,
	"name": "矿砂船",
	"url": "placeholder.png"
}, {
	"id": 9,
	"name": "驳船",
	"url": "placeholder.png"
}, {
	"id": 10,
	"name": "拖轮",
	"url": "placeholder.png"
}, {
	"id": 11,
	"name": "渔业船舶",
	"url": "placeholder.png"
}, {
	"id": 12,
	"name": "旅客船",
	"url": "placeholder.png"
}, {
	"id": 13,
	"name": "客滚船",
	"url": "placeholder.png"
}, {
	"id": 14,
	"name": "游轮",
	"url": "placeholder.png"
}, {
	"id": 15,
	"name": "滚装船",
	"url": "placeholder.png"
}, {
	"id": 16,
	"name": "沥青船",
	"url": "placeholder.png"
}, {
	"id": 17,
	"name": "挖泥船",
	"url": "placeholder.png"
}, {
	"id": 18,
	"name": "打桩船",
	"url": "placeholder.png"
}, {
	"id": 19,
	"name": "辅管船",
	"url": "placeholder.png"
}, {
	"id": 20,
	"name": "浮式起重船",
	"url": "placeholder.png"
}, {
	"id": 21,
	"name": "风电安装平台",
	"url": "placeholder.png"
}, {
	"id": 22,
	"name": "海洋平台",
	"url": "placeholder.png"
}, {
	"id": 23,
	"name": "海洋开发用船",
	"url": "placeholder.png"
}, {
	"id": 24,
	"name": "游艇",
	"url": "placeholder.png"
}, {
	"id": 25,
	"name": "油化船",
	"url": "placeholder.png"
}, {
	"id": 26,
	"name": "供水船",
	"url": "placeholder.png"
}, {
	"id": 27,
	"name": "冷藏船",
	"url": "placeholder.png"
}, {
	"id": 28,
	"name": "干货船",
	"url": "placeholder.png"
}, {
	"id": 29,
	"name": "工程船",
	"url": "placeholder.png"
}, {
	"id": 30,
	"name": "木材船",
	"url": "placeholder.png"
}, {
	"id": 31,
	"name": "水泥船",
	"url": "placeholder.png"
}, {
	"id": 32,
	"name": "小型船",
	"url": "placeholder.png"
}, {
	"id": 33,
	"name": "中型船",
	"url": "placeholder.png"
}, {
	"id": 34,
	"name": "大型船",
	"url": "placeholder.png"
}]